/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesquisaPosCursoRouteImport } from './routes/pesquisa-pos-curso'
import { Route as PesquisaInstitucionalRouteImport } from './routes/pesquisa-institucional'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PesquisaPosCursoRoute = PesquisaPosCursoRouteImport.update({
  id: '/pesquisa-pos-curso',
  path: '/pesquisa-pos-curso',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaInstitucionalRoute = PesquisaInstitucionalRouteImport.update({
  id: '/pesquisa-institucional',
  path: '/pesquisa-institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/obrigado': typeof ObrigadoRoute
  '/pesquisa': typeof PesquisaRoute
  '/pesquisa-institucional': typeof PesquisaInstitucionalRoute
  '/pesquisa-pos-curso': typeof PesquisaPosCursoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/obrigado': typeof ObrigadoRoute
  '/pesquisa': typeof PesquisaRoute
  '/pesquisa-institucional': typeof PesquisaInstitucionalRoute
  '/pesquisa-pos-curso': typeof PesquisaPosCursoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/obrigado': typeof ObrigadoRoute
  '/pesquisa': typeof PesquisaRoute
  '/pesquisa-institucional': typeof PesquisaInstitucionalRoute
  '/pesquisa-pos-curso': typeof PesquisaPosCursoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/obrigado'
    | '/pesquisa'
    | '/pesquisa-institucional'
    | '/pesquisa-pos-curso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/obrigado'
    | '/pesquisa'
    | '/pesquisa-institucional'
    | '/pesquisa-pos-curso'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/obrigado'
    | '/pesquisa'
    | '/pesquisa-institucional'
    | '/pesquisa-pos-curso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PesquisaRoute: typeof PesquisaRoute
  PesquisaInstitucionalRoute: typeof PesquisaInstitucionalRoute
  PesquisaPosCursoRoute: typeof PesquisaPosCursoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pesquisa-pos-curso': {
      id: '/pesquisa-pos-curso'
      path: '/pesquisa-pos-curso'
      fullPath: '/pesquisa-pos-curso'
      preLoaderRoute: typeof PesquisaPosCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-institucional': {
      id: '/pesquisa-institucional'
      path: '/pesquisa-institucional'
      fullPath: '/pesquisa-institucional'
      preLoaderRoute: typeof PesquisaInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ObrigadoRoute: ObrigadoRoute,
  PesquisaRoute: PesquisaRoute,
  PesquisaInstitucionalRoute: PesquisaInstitucionalRoute,
  PesquisaPosCursoRoute: PesquisaPosCursoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
