/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesquisaPosCursoRouteImport } from './routes/pesquisa-pos-curso'
import { Route as PesquisaInstitucionalRouteImport } from './routes/pesquisa-institucional'
import { Route as PesquisaAula5RouteImport } from './routes/pesquisa-aula-5'
import { Route as PesquisaAula4RouteImport } from './routes/pesquisa-aula-4'
import { Route as PesquisaAula3RouteImport } from './routes/pesquisa-aula-3'
import { Route as PesquisaAula2RouteImport } from './routes/pesquisa-aula-2'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AvaliacaoConvidadoRouteImport } from './routes/avaliacao-convidado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PesquisaPosCursoRoute = PesquisaPosCursoRouteImport.update({
  id: '/pesquisa-pos-curso',
  path: '/pesquisa-pos-curso',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaInstitucionalRoute = PesquisaInstitucionalRouteImport.update({
  id: '/pesquisa-institucional',
  path: '/pesquisa-institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaAula5Route = PesquisaAula5RouteImport.update({
  id: '/pesquisa-aula-5',
  path: '/pesquisa-aula-5',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaAula4Route = PesquisaAula4RouteImport.update({
  id: '/pesquisa-aula-4',
  path: '/pesquisa-aula-4',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaAula3Route = PesquisaAula3RouteImport.update({
  id: '/pesquisa-aula-3',
  path: '/pesquisa-aula-3',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaAula2Route = PesquisaAula2RouteImport.update({
  id: '/pesquisa-aula-2',
  path: '/pesquisa-aula-2',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoConvidadoRoute = AvaliacaoConvidadoRouteImport.update({
  id: '/avaliacao-convidado',
  path: '/avaliacao-convidado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliacao-convidado': typeof AvaliacaoConvidadoRoute
  '/obrigado': typeof ObrigadoRoute
  '/pesquisa': typeof PesquisaRoute
  '/pesquisa-aula-2': typeof PesquisaAula2Route
  '/pesquisa-aula-3': typeof PesquisaAula3Route
  '/pesquisa-aula-4': typeof PesquisaAula4Route
  '/pesquisa-aula-5': typeof PesquisaAula5Route
  '/pesquisa-institucional': typeof PesquisaInstitucionalRoute
  '/pesquisa-pos-curso': typeof PesquisaPosCursoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliacao-convidado': typeof AvaliacaoConvidadoRoute
  '/obrigado': typeof ObrigadoRoute
  '/pesquisa': typeof PesquisaRoute
  '/pesquisa-aula-2': typeof PesquisaAula2Route
  '/pesquisa-aula-3': typeof PesquisaAula3Route
  '/pesquisa-aula-4': typeof PesquisaAula4Route
  '/pesquisa-aula-5': typeof PesquisaAula5Route
  '/pesquisa-institucional': typeof PesquisaInstitucionalRoute
  '/pesquisa-pos-curso': typeof PesquisaPosCursoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliacao-convidado': typeof AvaliacaoConvidadoRoute
  '/obrigado': typeof ObrigadoRoute
  '/pesquisa': typeof PesquisaRoute
  '/pesquisa-aula-2': typeof PesquisaAula2Route
  '/pesquisa-aula-3': typeof PesquisaAula3Route
  '/pesquisa-aula-4': typeof PesquisaAula4Route
  '/pesquisa-aula-5': typeof PesquisaAula5Route
  '/pesquisa-institucional': typeof PesquisaInstitucionalRoute
  '/pesquisa-pos-curso': typeof PesquisaPosCursoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliacao-convidado'
    | '/obrigado'
    | '/pesquisa'
    | '/pesquisa-aula-2'
    | '/pesquisa-aula-3'
    | '/pesquisa-aula-4'
    | '/pesquisa-aula-5'
    | '/pesquisa-institucional'
    | '/pesquisa-pos-curso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avaliacao-convidado'
    | '/obrigado'
    | '/pesquisa'
    | '/pesquisa-aula-2'
    | '/pesquisa-aula-3'
    | '/pesquisa-aula-4'
    | '/pesquisa-aula-5'
    | '/pesquisa-institucional'
    | '/pesquisa-pos-curso'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliacao-convidado'
    | '/obrigado'
    | '/pesquisa'
    | '/pesquisa-aula-2'
    | '/pesquisa-aula-3'
    | '/pesquisa-aula-4'
    | '/pesquisa-aula-5'
    | '/pesquisa-institucional'
    | '/pesquisa-pos-curso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvaliacaoConvidadoRoute: typeof AvaliacaoConvidadoRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PesquisaRoute: typeof PesquisaRoute
  PesquisaAula2Route: typeof PesquisaAula2Route
  PesquisaAula3Route: typeof PesquisaAula3Route
  PesquisaAula4Route: typeof PesquisaAula4Route
  PesquisaAula5Route: typeof PesquisaAula5Route
  PesquisaInstitucionalRoute: typeof PesquisaInstitucionalRoute
  PesquisaPosCursoRoute: typeof PesquisaPosCursoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pesquisa-pos-curso': {
      id: '/pesquisa-pos-curso'
      path: '/pesquisa-pos-curso'
      fullPath: '/pesquisa-pos-curso'
      preLoaderRoute: typeof PesquisaPosCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-institucional': {
      id: '/pesquisa-institucional'
      path: '/pesquisa-institucional'
      fullPath: '/pesquisa-institucional'
      preLoaderRoute: typeof PesquisaInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-aula-5': {
      id: '/pesquisa-aula-5'
      path: '/pesquisa-aula-5'
      fullPath: '/pesquisa-aula-5'
      preLoaderRoute: typeof PesquisaAula5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-aula-4': {
      id: '/pesquisa-aula-4'
      path: '/pesquisa-aula-4'
      fullPath: '/pesquisa-aula-4'
      preLoaderRoute: typeof PesquisaAula4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-aula-3': {
      id: '/pesquisa-aula-3'
      path: '/pesquisa-aula-3'
      fullPath: '/pesquisa-aula-3'
      preLoaderRoute: typeof PesquisaAula3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa-aula-2': {
      id: '/pesquisa-aula-2'
      path: '/pesquisa-aula-2'
      fullPath: '/pesquisa-aula-2'
      preLoaderRoute: typeof PesquisaAula2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao-convidado': {
      id: '/avaliacao-convidado'
      path: '/avaliacao-convidado'
      fullPath: '/avaliacao-convidado'
      preLoaderRoute: typeof AvaliacaoConvidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvaliacaoConvidadoRoute: AvaliacaoConvidadoRoute,
  ObrigadoRoute: ObrigadoRoute,
  PesquisaRoute: PesquisaRoute,
  PesquisaAula2Route: PesquisaAula2Route,
  PesquisaAula3Route: PesquisaAula3Route,
  PesquisaAula4Route: PesquisaAula4Route,
  PesquisaAula5Route: PesquisaAula5Route,
  PesquisaInstitucionalRoute: PesquisaInstitucionalRoute,
  PesquisaPosCursoRoute: PesquisaPosCursoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
